spring.application.name=boardgame-rpc-kotlin
server.port=${PORT:8080}
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/openapi.json
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

